<a href="https://colab.research.google.com/github/o-bissing/TF_Udemy/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
path_to_file = 'shakespeare.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [4]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

# Text processing

In [6]:
vocab = sorted(set(text))

In [7]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

In [9]:
for pair in enumerate(vocab):
  print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [10]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}

In [11]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [12]:
char_to_ind['H']

33

In [13]:
ind_to_char = np.array(vocab)

In [14]:
ind_to_char[33]

'H'

In [15]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [17]:
encoded_text.shape

(5445609,)

In [18]:
sample = text[:500]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [19]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

# Creating batches

In [20]:
seq_len = 120

In [21]:
total_num_seq = len(text) // (seq_len+1)
total_num_seq

45005

In [22]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [23]:
type(char_dataset)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [24]:
for item in char_dataset.take(500):
  print(item.numpy())

0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
12
0
1
1
31
73
70
68
1
61
56
64
73
60
74
75
1
58
73
60
56
75
76
73
60
74
1
78
60
1
59
60
74
64
73
60
1
64
69
58
73
60
56
74
60
8
0
1
1
45
63
56
75
1
75
63
60
73
60
57
80
1
57
60
56
76
75
80
5
74
1
73
70
74
60
1
68
64
62
63
75
1
69
60
77
60
73
1
59
64
60
8
0
1
1
27
76
75
1
56
74
1
75
63
60
1
73
64
71
60
73
1
74
63
70
76
67
59
1
57
80
1
75
64
68
60
1
59
60
58
60
56
74
60
8
0
1
1
33
64
74
1
75
60
69
59
60
73
1
63
60
64
73
1
68
64
62
63
75
1
57
60
56
73
1
63
64
74
1
68
60
68
70
73
80
21
0
1
1
27
76
75
1
75
63
70
76
1
58
70
69
75
73
56
58
75
60
59
1
75
70
1
75
63
64
69
60
1
70
78
69
1
57
73
64
62
63
75
1
60
80
60
74
8
0
1
1
31
60
60
59
5
74
75
1
75
63
80
1
67
64
62
63
75
5
74
1
61
67
56
68
60
1
78
64
75
63
1
74
60
67
61
9
74
76
57
74
75
56
69
75
64
56
67
1
61
76
60
67
8
0
1
1
38
56
66
64
69
62
1
56
1
61
56
68
64
69
60
1
78
63
60
73
60
1
56
57
76
69
59
56
69
58
60
1
67
64
60
74
8
0
1
1
45
63
80
1
74
60
67
61
1
75
63
80
1
61
70
60
8
1
75
70
1
75
63


In [25]:
sequences = char_dataset.batch(seq_len+1,drop_remainder=True)

In [27]:
def create_seq_targets(seq):
  input_txt = seq[:-1]
  target_txt = seq[1:]
  return input_txt,target_txt

In [28]:
dataset = sequences.map(create_seq_targets)

In [29]:
for input_txt,target_txt in dataset.take(1):
  print(input_txt.numpy())
  print("".join(ind_to_char[input_txt.numpy()]))
  print('\n')
  print(target_txt.numpy())
  print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [30]:
batch_size = 128

In [44]:
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [45]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

# Creating a model

In [33]:
vocab_size = len(vocab)

In [34]:
vocab_size

84

In [35]:
embed_dim = 64

In [36]:
rnn_neurons = 1026

In [37]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [38]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [40]:
def create_model(vocab_size,embed_dim,rnn_neurons,batch_size):
  model = Sequential()
  model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
  model.add(GRU(rnn_neurons,return_sequences=True,
                stateful=True,recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  model.compile('adam',loss=sparse_cat_loss)

  return model

In [46]:
model = create_model(vocab_size=vocab_size,
                     embed_dim=embed_dim,
                     rnn_neurons=rnn_neurons,
                     batch_size=batch_size)

In [47]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (128, None, 64)           5376      
                                                                 
 gru_1 (GRU)                 (128, None, 1026)         3361176   
                                                                 
 dense_1 (Dense)             (128, None, 84)           86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Training the model

In [48]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)

In [49]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [50]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.0040932 ,  0.00326143,  0.0007041 , ..., -0.00221342,
        -0.00130124, -0.00236011],
       [-0.00112935,  0.00233402, -0.00201602, ..., -0.00766347,
        -0.00048478, -0.00211245],
       [-0.00162862, -0.00464133, -0.00369455, ..., -0.00572149,
        -0.00750485, -0.00241369],
       ...,
       [ 0.00416069,  0.00456692, -0.00350668, ..., -0.00850858,
         0.00037231, -0.00051463],
       [ 0.00143103, -0.00087979, -0.00085839, ..., -0.01179023,
        -0.00349675,  0.00148903],
       [ 0.00245988, -0.00194473,  0.00463058, ..., -0.01280639,
        -0.00661534, -0.00262771]], dtype=float32)>

In [51]:
sampled_indices = tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [52]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[30],
       [30],
       [25],
       [79],
       [55],
       [27],
       [65],
       [10],
       [62],
       [41],
       [36],
       [55],
       [77],
       [51],
       [42],
       [12],
       [ 8],
       [50],
       [61],
       [43],
       [18],
       [50],
       [66],
       [ 3],
       [53],
       [59],
       [18],
       [63],
       [82],
       [24],
       [59],
       [16],
       [65],
       [63],
       [51],
       [79],
       [17],
       [30],
       [ 3],
       [61],
       [ 2],
       [58],
       [19],
       [34],
       [10],
       [55],
       [13],
       [48],
       [23],
       [ 6],
       [ 4],
       [49],
       [19],
       [18],
       [65],
       [81],
       [49],
       [53],
       [64],
       [27],
       [36],
       [67],
       [ 8],
       [67],
       [56],
       [70],
       [58],
       [ 7],
       [11],
       [65],
       [59],
       [44],
       [78],
   

In [53]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [54]:
sampled_indices

array([30, 30, 25, 79, 55, 27, 65, 10, 62, 41, 36, 55, 77, 51, 42, 12,  8,
       50, 61, 43, 18, 50, 66,  3, 53, 59, 18, 63, 82, 24, 59, 16, 65, 63,
       51, 79, 17, 30,  3, 61,  2, 58, 19, 34, 10, 55, 13, 48, 23,  6,  4,
       49, 19, 18, 65, 81, 49, 53, 64, 27, 36, 67,  8, 67, 56, 70, 58,  7,
       11, 65, 59, 44, 78, 82, 70, 10, 25, 48, 27, 45, 50, 43, 47, 41, 41,
       27, 38, 81, 39, 43,  6, 74, 67, 14, 64, 37, 83,  7,  3,  8, 22, 60,
        2, 17, 80, 73, 15, 51, 68, 65, 48, 51,  5, 64, 68, 22,  2, 78, 40,
       78])

In [55]:
ind_to_char[sampled_indices]

array(['E', 'E', '?', 'x', '`', 'B', 'j', '.', 'g', 'P', 'K', '`', 'v',
       'Z', 'Q', '1', ',', 'Y', 'f', 'R', '7', 'Y', 'k', '"', ']', 'd',
       '7', 'h', '|', '>', 'd', '5', 'j', 'h', 'Z', 'x', '6', 'E', '"',
       'f', '!', 'c', '8', 'I', '.', '`', '2', 'W', '<', '(', '&', 'X',
       '8', '7', 'j', 'z', 'X', ']', 'i', 'B', 'K', 'l', ',', 'l', 'a',
       'o', 'c', ')', '0', 'j', 'd', 'S', 'w', '|', 'o', '.', '?', 'W',
       'B', 'T', 'Y', 'R', 'V', 'P', 'P', 'B', 'M', 'z', 'N', 'R', '(',
       's', 'l', '3', 'i', 'L', '}', ')', '"', ',', ';', 'e', '!', '6',
       'y', 'r', '4', 'Z', 'm', 'j', 'W', 'Z', "'", 'i', 'm', ';', '!',
       'w', 'O', 'w'], dtype='<U1')

In [56]:
epochs = 30

In [57]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
  5/351 [..............................] - ETA: 43:43 - loss: 5.4282

KeyboardInterrupt: ignored

In [58]:
from tensorflow.keras.models import load_model

In [59]:
model = create_model(vocab_size,embed_dim,rnn_neurons,batch_size=1)
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1,None]))

In [60]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_2 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_2 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [61]:
def generate_text(model,start_seed,gen_size=500,temp=1.0):
  num_generate = gen_size
  input_eval = [char_to_ind[s] for s in start_seed]
  input_eval = tf.expand_dims(input_eval,0)
  text_generated = []
  temperature = temp
  model.reset_states()

  for i in range(num_generate):
    predictions = model(input_eval)
    predictions = tf.squeeze(predictions,0)
    predictions = predictions/temperature
    predicted_id = tf.random.categorical(predictions,num_samples=1)[-1,0].numpy()
    input_eval = tf.expand_dims([predicted_id],0)
    text_generated.append(ind_to_char[predicted_id])

  return (start_seed+"".join(text_generated))

In [62]:
print(generate_text(model,"JULIET",gen_size=1000))

JULIETHEN, with his French tripple than he that holds in the
     amazement for gone and obey my knee. Pray you, sir knock what
    ince but loathe thee of my most humble hand, this comes his rud;
    My heart blood and his last. Is fair it not?
  ANNE. Now down your will! I will
    bring them to preserve for Cupid and keep or no;
    Henry conquerers do to-earned man!
    And yet, Place, wept more, of this island,
    What will revears urshore attends the door?
  TROILUS. Very well;
    Where is the grafe of your best love?
  MESSALA. There is no bitter won.
  POLIXENES. His end em  What is the Duke's with holy precious
    Shall raise so still to kiss, the scarce cords;
    O, when with him this jewel doth but seeming!
  VIOLA. No, not amen!
  PANDARUS. I shall answard me. Welcome, good sweet Duke, if it be
    that your rage makes for fear; but, sir, with Jann cover'd Duke.
  EPCLip HISTRIBUTED OR USED
COMMERCIALLY.  PROHIBITED COMMERCIAL DISTRIBUTION INCLUDES BY ANY
SERVICE THAT C