<a href="https://colab.research.google.com/github/o-bissing/TF_Udemy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [ ]:
# create np array from a normal one
np.array(mylist)

array([1, 2, 3])

In [10]:
nested_list = [[1,2], [3,4], [5,6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [11]:
# create np array from a nested normal one
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# create np array with start, stop and step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# create an array of numbers
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [20]:
# create an array with evenly spaced points with start, stop and step
# !!! INCLUDES THE STOP POINT
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [22]:
# create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# random array with uniform distribution (same likehood) between 0 and 1
np.random.rand(5)

array([0.68494033, 0.04102329, 0.39635813, 0.83269385, 0.3589847 ])

In [26]:
# random matrix with uniform distribution (same likehood) between 0 and 1
np.random.rand(3,4)

array([[0.61902651, 0.66202191, 0.99354605, 0.9235934 ],
       [0.25092012, 0.02138719, 0.19480341, 0.2486565 ],
       [0.44461504, 0.42853658, 0.35353771, 0.34691305]])

In [28]:
# random array with standart normal distribution (mean 0, variance 1) between -1 and 1
np.random.randn(5,5)

array([[-0.47392109, -1.11283307, -0.37689536, -1.3872908 , -0.47300834],
       [ 1.30401079,  0.40098189, -0.73736783, -0.37460378, -0.45459731],
       [-1.02549254,  0.82524447, -0.48305089,  0.23855329, -1.10591352],
       [-0.49415507,  1.35425865,  0.13003915, -0.42301394, -1.25766567],
       [ 0.57792187,  0.6405755 , -0.12299881,  0.09031858,  0.00583812]])

In [32]:
# random array of integers (low, high, quantity)
np.random.randint(1,100,10)

array([19, 41, 49, 24, 36, 70, 63, 57, 69, 17])

In [33]:
np.random.randint(1,100,(2,3))

array([[26, 86, 42],
       [31, 36, 67]])

In [36]:
# random seed, to generate same randoms on each PC, generation (iteration) is important
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
# reshape
arr = np.arange(25)

In [38]:
ranarr = np.random.randint(0,50,10)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [41]:
arr.shape

(25,)

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
# maxvalue
ranarr.max()

39

In [45]:
# position of the max value
ranarr.argmax()

7

In [46]:
# datatype
ranarr.dtype

dtype('int64')